#!/bin/bash -e
source $(dirname $0)/../install-lib.sh

if [ -z "$GOROOT" ]; then
    echo "Please set \$GOROOT in ~/dotfiles/.bashrc.local" >& 2
fi

mkdir -p "$HOME/go/src/github.com/$GITHUB_USERNAME"
mkdir -p "$HOME/go/src/testbed"
mod_enable sh golang.sh
mod_enable vim golang.vim

